#!/usr/bin/env python3
"""Interactive first-run setup. Gets you from a fresh clone to a notifying bot.

Run via:  python3 run.py setup   (or)   python3 setup.py

Steps: generate an ntfy topic + write .env, show subscribe instructions, send a
test push, and optionally install the scheduler (launchd on macOS) with your own
paths filled in. Zero dependencies.
"""
from __future__ import annotations

import json
import os
import platform
import secrets
import subprocess
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def _c(text: str, code: str) -> str:
    return text if not sys.stdout.isatty() else f"\033[{code}m{text}\033[0m"


def bold(t: str) -> str:
    return _c(t, "1")


def green(t: str) -> str:
    return _c(t, "32")


def dim(t: str) -> str:
    return _c(t, "2")


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        ans = ""
    return ans or default


def yes(prompt: str, default: bool = True) -> bool:
    d = "Y/n" if default else "y/N"
    ans = ask(f"{prompt} ({d})").lower()
    if not ans:
        return default
    return ans.startswith("y")


def write_env() -> dict:
    """Create/overwrite .env. Returns the chosen settings dict."""
    env_path = os.path.join(BASE_DIR, ".env")
    if os.path.exists(env_path) and not yes(
        "\n.env already exists. Overwrite it?", default=False
    ):
        print(dim("Keeping existing .env."))
        return {}

    print(bold("\n1. Notification channel (ntfy)"))
    print(dim("   Alerts are pushed to a private ntfy topic you subscribe to on your phone."))
    suggested = "depop-" + secrets.token_urlsafe(9)
    topic = ask("   Topic name (any unguessable string)", default=suggested)
    server = ask("   ntfy server", default="https://ntfy.sh")

    print(bold("\n2. LLM judging (optional)"))
    print(dim("   An Anthropic API key lets the bot judge ambiguous 'maybe' listings."))
    print(dim("   Leave blank to run on rules only (still fully functional, $0)."))
    api_key = ask("   ANTHROPIC_API_KEY (blank to skip)")

    lines = [
        "# Generated by setup.py",
        f"NTFY_TOPIC={topic}",
        f"NTFY_SERVER={server}",
    ]
    if api_key:
        lines.append(f"ANTHROPIC_API_KEY={api_key}")
    else:
        lines.append("# ANTHROPIC_API_KEY=sk-ant-...")
    with open(env_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.environ["NTFY_TOPIC"] = topic
    os.environ["NTFY_SERVER"] = server
    if api_key:
        os.environ["ANTHROPIC_API_KEY"] = api_key
    print(green(f"   ✓ Wrote {env_path}"))
    return {"topic": topic, "server": server}


def choose_preset() -> None:
    """List presets/*.json and write the chosen one into config.json."""
    presets_dir = os.path.join(BASE_DIR, "presets")
    if not os.path.isdir(presets_dir):
        return
    presets = sorted(f[:-5] for f in os.listdir(presets_dir) if f.endswith(".json"))
    if not presets:
        return

    print(bold("\n3. Category"))
    print(dim("   Each preset bundles search queries + a value rubric for one category."))
    metas = {}
    for i, name in enumerate(presets, 1):
        try:
            with open(os.path.join(presets_dir, f"{name}.json")) as f:
                metas[name] = json.load(f).get("description", "")
        except Exception:
            metas[name] = ""
        print(f"   {i}) {name:<10} {dim(metas[name])}")
    default = "hats" if "hats" in presets else presets[0]
    chosen = ""
    while chosen not in presets:
        ans = ask("   Pick a number or name", default=default)
        if ans.isdigit() and 1 <= int(ans) <= len(presets):
            chosen = presets[int(ans) - 1]
        elif ans in presets:
            chosen = ans
        else:
            chosen = default

    cfg_path = os.path.join(BASE_DIR, "config.json")
    try:
        with open(cfg_path) as f:
            cfg = json.load(f)
        cfg["preset"] = chosen
        with open(cfg_path, "w") as f:
            json.dump(cfg, f, indent=2)
        print(green(f"   ✓ Set preset to '{chosen}' in config.json"))
    except Exception as e:
        print(f"   ✗ Could not update config.json: {e}")
        print(dim(f"   Set \"preset\": \"{chosen}\" manually."))


def show_subscribe(settings: dict) -> None:
    topic = settings.get("topic") or os.environ.get("NTFY_TOPIC", "")
    server = settings.get("server") or os.environ.get("NTFY_SERVER", "https://ntfy.sh")
    if not topic:
        return
    print(bold("\n4. Subscribe on your phone"))
    print("   a) Install the ntfy app (iOS App Store / Google Play / F-Droid)")
    print(f"   b) Add a subscription to topic:  {green(topic)}")
    print(f"   c) Or open in a browser:  {server}/{topic}")


def send_test(settings: dict) -> None:
    if not os.environ.get("NTFY_TOPIC"):
        return
    print(bold("\n5. Test notification"))
    if not yes("   Send a test notification now?", default=True):
        return
    try:
        from notify import notify

        notify(
            "depop-scraper is set up ✅",
            "If you see this, alerts are working. Happy hunting.",
            url="https://github.com/SuvanD0/depop-scraper",
            priority="high",
        )
        print(green("   ✓ Sent. Check your phone (and confirm the subscription took)."))
    except Exception as e:
        print(f"   ✗ Test failed: {e}")
        print(dim("   Double-check the topic and that your device is subscribed."))


PLIST_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python}</string>
        <string>{script}</string>
    </array>
    <key>StartInterval</key>
    <integer>{interval}</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{logpath}</string>
    <key>StandardErrorPath</key>
    <string>{logpath}</string>
    <key>WorkingDirectory</key>
    <string>{workdir}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
"""


def install_scheduler() -> None:
    if platform.system() != "Darwin":
        print(bold("\n6. Scheduling"))
        print(dim("   Not on macOS — add a cron entry or systemd timer that runs:"))
        print(f"     {sys.executable} {os.path.join(BASE_DIR, 'run.py')}")
        return

    print(bold("\n6. Run on a schedule (launchd)"))
    if not yes("   Install a launchd agent to run automatically?", default=True):
        print(dim("   Skipped. You can run manually with: python3 run.py --loop"))
        return

    try:
        with open(os.path.join(BASE_DIR, "config.json")) as f:
            cadence = json.load(f).get("cadence_minutes", 30)
    except Exception:
        cadence = 30

    label = "com.depop-scraper"
    plist = PLIST_TEMPLATE.format(
        label=label,
        python=sys.executable,
        script=os.path.join(BASE_DIR, "run.py"),
        interval=int(cadence) * 60,
        logpath=os.path.join(BASE_DIR, "run.log"),
        workdir=BASE_DIR,
    )
    dest = os.path.expanduser(f"~/Library/LaunchAgents/{label}.plist")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        f.write(plist)
    print(green(f"   ✓ Wrote {dest}"))

    subprocess.run(["launchctl", "unload", dest], capture_output=True)
    res = subprocess.run(["launchctl", "load", dest], capture_output=True, text=True)
    if res.returncode == 0:
        print(green(f"   ✓ Loaded — runs now and every {cadence} min."))
    else:
        print(f"   ✗ launchctl load failed: {res.stderr.strip()}")
        print(dim(f"   Load it manually: launchctl load {dest}"))


def main() -> None:
    print(bold("\n  depop-scraper setup\n  " + "─" * 21))
    if not sys.stdin.isatty():
        print("Setup needs an interactive terminal. Run: python3 run.py setup")
        sys.exit(1)

    settings = write_env()
    choose_preset()
    show_subscribe(settings)
    send_test(settings)
    install_scheduler()

    print(bold("\n  Done.") + dim("  Next:"))
    print("   • python3 run.py --dry-run     test scoring, no alerts")
    print("   • python3 run.py               one real pass")
    print("   • edit config.json             change queries / price / cadence")
    print("   • edit value_rubric.json       change what counts as valuable\n")


if __name__ == "__main__":
    main()
